In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/train.csv")
df.head(15)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0    1          60       RL         65.0     8450   Pave   NaN      Reg   
1    2          20       RL         80.0     9600   Pave   NaN      Reg   
2    3          60       RL         68.0    11250   Pave   NaN      IR1   
3    4          70       RL         60.0     9550   Pave   NaN      IR1   
4    5          60       RL         84.0    14260   Pave   NaN      IR1   
5    6          50       RL         85.0    14115   Pave   NaN      IR1   
6    7          20       RL         75.0    10084   Pave   NaN      Reg   
7    8          60       RL          NaN    10382   Pave   NaN      IR1   
8    9          50       RM         51.0     6120   Pave   NaN      Reg   
9   10         190       RL         50.0     7420   Pave   NaN      Reg   
10  11          20       RL         70.0    11200   Pave   NaN      Reg   
11  12          60       RL         85.0    11924   Pave   NaN      IR1   
12  13          20       RL          NaN    12968   Pave   NaN      IR2   
13  14          20       RL         91.0    10652   Pave   NaN      IR1   
14  15          20       RL          NaN    10920   Pave   NaN      IR1   

   LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0          Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1          Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2          Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3          Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4          Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
5          Lvl    AllPub  ...        0    NaN  MnPrv        Shed     700   
6          Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
7          Lvl    AllPub  ...        0    NaN    NaN        Shed     350   
8          Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
9          Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
10         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
11         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
12         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
13         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
14         Lvl    AllPub  ...        0    NaN   GdWo         NaN       0   

   MoSold YrSold  SaleType  SaleCondition  SalePrice  
0       2   2008        WD         Normal     208500  
1       5   2007        WD         Normal     181500  
2       9   2008        WD         Normal     223500  
3       2   2006        WD        Abnorml     140000  
4      12   2008        WD         Normal     250000  
5      10   2009        WD         Normal     143000  
6       8   2007        WD         Normal     307000  
7      11   2009        WD         Normal     200000  
8       4   2008        WD        Abnorml     129900  
9       1   2008        WD         Normal     118000  
10      2   2008        WD         Normal     129500  
11      7   2006       New        Partial     345000  
12      9   2008        WD         Normal     144000  
13      8   2007       New        Partial     279500  
14      5   2008        WD         Normal     157000  

[15 rows x 81 columns]

In [2]:
print(df.shape)
print(pd.DataFrame({
    'Missing': df.isnull().sum(),
    'Percent': (df.isnull().sum() / len(df) * 100).round(2)
}).sort_values('Missing', ascending=False))

(1460, 81)
               Missing  Percent
PoolQC            1453    99.52
MiscFeature       1406    96.30
Alley             1369    93.77
Fence             1179    80.75
MasVnrType         872    59.73
...                ...      ...
MoSold               0     0.00
YrSold               0     0.00
SaleType             0     0.00
SaleCondition        0     0.00
SalePrice            0     0.00

[81 rows x 2 columns]


In [3]:
df['PoolQC'].unique()

array([nan, 'Ex', 'Fa', 'Gd'], dtype=object)

In [4]:
df['PoolQC'] = df['PoolQC'].fillna('None')
pool_mapping = {'None': 0, 'Fa': 1, 'TA': 2, 'Gd': 3, 'Ex': 4}
df['PoolQC'] = df['PoolQC'].map(pool_mapping)
print(pd.DataFrame({
    'Missing': df.isnull().sum(),
    'Percent': (df.isnull().sum() / len(df) * 100).round(2)
}).sort_values('Missing', ascending=False))

               Missing  Percent
MiscFeature       1406    96.30
Alley             1369    93.77
Fence             1179    80.75
MasVnrType         872    59.73
FireplaceQu        690    47.26
...                ...      ...
MoSold               0     0.00
YrSold               0     0.00
SaleType             0     0.00
SaleCondition        0     0.00
SalePrice            0     0.00

[81 rows x 2 columns]


In [5]:
df['MiscFeature'].unique()

array([nan, 'Shed', 'Gar2', 'Othr', 'TenC'], dtype=object)

In [6]:
df['Alley'].unique()

array([nan, 'Grvl', 'Pave'], dtype=object)

In [7]:
df['Fence'].unique()

array([nan, 'MnPrv', 'GdWo', 'GdPrv', 'MnWw'], dtype=object)

In [8]:
df['MasVnrType'].unique()

array(['BrkFace', nan, 'Stone', 'BrkCmn'], dtype=object)

In [9]:
df['FireplaceQu'] = df['FireplaceQu'].fillna('None')
df['FireplaceQu'].unique()

array(['None', 'TA', 'Gd', 'Fa', 'Ex', 'Po'], dtype=object)

In [10]:
fp_mapping = {'None': 0, 'Po': 1, 'Fa': 2, 'TA': 3, 'Gd': 4, 'Ex': 5}
df['FireplaceQu'] = df['FireplaceQu'].map(fp_mapping)

In [11]:
# one-hot encoding for nominal categorical variables
df = pd.get_dummies(df, columns=['MiscFeature'], prefix='MiscFeature', dummy_na=False, dtype=int)
df = pd.get_dummies(df, columns=['Alley'], prefix='Alley', dummy_na=False, dtype=int)
df = pd.get_dummies(df, columns=['Fence'], prefix='Fence', dummy_na=False, dtype=int)
df = pd.get_dummies(df, columns=['MasVnrType'], prefix='MasVnrType', dummy_na=False, dtype=int)

df.head(50)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0    1          60       RL         65.0     8450   Pave      Reg         Lvl   
1    2          20       RL         80.0     9600   Pave      Reg         Lvl   
2    3          60       RL         68.0    11250   Pave      IR1         Lvl   
3    4          70       RL         60.0     9550   Pave      IR1         Lvl   
4    5          60       RL         84.0    14260   Pave      IR1         Lvl   
5    6          50       RL         85.0    14115   Pave      IR1         Lvl   
6    7          20       RL         75.0    10084   Pave      Reg         Lvl   
7    8          60       RL          NaN    10382   Pave      IR1         Lvl   
8    9          50       RM         51.0     6120   Pave      Reg         Lvl   
9   10         190       RL         50.0     7420   Pave      Reg         Lvl   
10  11          20       RL         70.0    11200   Pave      Reg         Lvl   
11  12          60       RL         85.0    11924   Pave      IR1         Lvl   
12  13          20       RL          NaN    12968   Pave      IR2         Lvl   
13  14          20       RL         91.0    10652   Pave      IR1         Lvl   
14  15          20       RL          NaN    10920   Pave      IR1         Lvl   
15  16          45       RM         51.0     6120   Pave      Reg         Lvl   
16  17          20       RL          NaN    11241   Pave      IR1         Lvl   
17  18          90       RL         72.0    10791   Pave      Reg         Lvl   
18  19          20       RL         66.0    13695   Pave      Reg         Lvl   
19  20          20       RL         70.0     7560   Pave      Reg         Lvl   
20  21          60       RL        101.0    14215   Pave      IR1         Lvl   
21  22          45       RM         57.0     7449   Pave      Reg         Bnk   
22  23          20       RL         75.0     9742   Pave      Reg         Lvl   
23  24         120       RM         44.0     4224   Pave      Reg         Lvl   
24  25          20       RL          NaN     8246   Pave      IR1         Lvl   
25  26          20       RL        110.0    14230   Pave      Reg         Lvl   
26  27          20       RL         60.0     7200   Pave      Reg         Lvl   
27  28          20       RL         98.0    11478   Pave      Reg         Lvl   
28  29          20       RL         47.0    16321   Pave      IR1         Lvl   
29  30          30       RM         60.0     6324   Pave      IR1         Lvl   
30  31          70  C (all)         50.0     8500   Pave      Reg         Lvl   
31  32          20       RL          NaN     8544   Pave      IR1         Lvl   
32  33          20       RL         85.0    11049   Pave      Reg         Lvl   
33  34          20       RL         70.0    10552   Pave      IR1         Lvl   
34  35         120       RL         60.0     7313   Pave      Reg         Lvl   
35  36          60       RL        108.0    13418   Pave      Reg         Lvl   
36  37          20       RL        112.0    10859   Pave      Reg         Lvl   
37  38          20       RL         74.0     8532   Pave      Reg         Lvl   
38  39          20       RL         68.0     7922   Pave      Reg         Lvl   
39  40          90       RL         65.0     6040   Pave      Reg         Lvl   
40  41          20       RL         84.0     8658   Pave      Reg         Lvl   
41  42          20       RL        115.0    16905   Pave      Reg         Lvl   
42  43          85       RL          NaN     9180   Pave      IR1         Lvl   
43  44          20       RL          NaN     9200   Pave      IR1         Lvl   
44  45          20       RL         70.0     7945   Pave      Reg         Lvl   
45  46         120       RL         61.0     7658   Pave      Reg         Lvl   
46  47          50       RL         48.0    12822   Pave      IR1         Lvl   
47  48          20       FV         84.0    11096   Pave      Reg         Lvl   
48  49         190       RM        

In [12]:
print(pd.DataFrame({
    'Missing': df.isnull().sum(),
    'Percent': (df.isnull().sum() / len(df) * 100).round(2)
}).sort_values('Missing', ascending=False))

                    Missing  Percent
LotFrontage             259    17.74
GarageType               81     5.55
GarageFinish             81     5.55
GarageQual               81     5.55
GarageYrBlt              81     5.55
...                     ...      ...
Fence_MnPrv               0     0.00
Fence_MnWw                0     0.00
MasVnrType_BrkCmn         0     0.00
MasVnrType_BrkFace        0     0.00
MasVnrType_Stone          0     0.00

[90 rows x 2 columns]


In [13]:
df['LotFrontage'] = df['LotFrontage'].fillna(0)
df['GarageType'].unique()

array(['Attchd', 'Detchd', 'BuiltIn', 'CarPort', nan, 'Basment', '2Types'],
      dtype=object)

In [14]:
df = pd.get_dummies(df, columns=['GarageType'], prefix='GarageType', dummy_na=False, dtype=int)

df['GarageFinish'] = df['GarageFinish'].fillna('None')
gar_fin_mapping = {'None': 0, 'Unf': 1, 'RFn': 2, 'Fin': 3}
df['GarageFinish'] = df['GarageFinish'].map(gar_fin_mapping)

df['GarageQual'] = df['GarageQual'].fillna('None')
df['GarageCond'] = df['GarageCond'].fillna('None')
df['GarageQual'] = df['GarageQual'].map(fp_mapping)
df['GarageCond'] = df['GarageCond'].map(fp_mapping)

df['GarageYrBlt'] = df['GarageYrBlt'].fillna(df['YearBuilt'])

In [15]:
print(pd.DataFrame({
    'Missing': df.isnull().sum(),
    'Percent': (df.isnull().sum() / len(df) * 100).round(2)
}).sort_values('Missing', ascending=False))

                    Missing  Percent
BsmtExposure             38     2.60
BsmtFinType2             38     2.60
BsmtQual                 37     2.53
BsmtFinType1             37     2.53
BsmtCond                 37     2.53
...                     ...      ...
GarageType_Attchd         0     0.00
GarageType_Basment        0     0.00
GarageType_BuiltIn        0     0.00
GarageType_CarPort        0     0.00
GarageType_Detchd         0     0.00

[95 rows x 2 columns]


In [16]:
df['BsmtExposure'] = df['BsmtExposure'].fillna('None')
bexp_mapping = {'None': 0, 'No': 1, 'Mn': 2, 'Av': 3, 'Gd': 4}
df['BsmtExposure'] = df['BsmtExposure'].map(bexp_mapping)

df['BsmtFinType1'] = df['BsmtFinType1'].fillna('None')
df['BsmtFinType2'] = df['BsmtFinType2'].fillna('None')
bfin_mapping = {'None': 0, 'Unf': 1, 'LwQ': 2, 'Rec': 3, 'BLQ': 4, 'ALQ': 5, 'GLQ':6}
df['BsmtFinType1'] = df['BsmtFinType1'].map(bfin_mapping)
df['BsmtFinType2'] = df['BsmtFinType2'].map(bfin_mapping)

df['BsmtQual'] = df['BsmtQual'].fillna('None')
df['BsmtCond'] = df['BsmtCond'].fillna('None')
df['BsmtQual'] = df['BsmtQual'].map(fp_mapping)
df['BsmtCond'] = df['BsmtCond'].map(fp_mapping)

In [17]:
print(pd.DataFrame({
    'Missing': df.isnull().sum(),
    'Percent': (df.isnull().sum() / len(df) * 100).round(2)
}).sort_values('Missing', ascending=False))

                    Missing  Percent
MasVnrArea                8     0.55
Electrical                1     0.07
MSSubClass                0     0.00
LotFrontage               0     0.00
LotArea                   0     0.00
...                     ...      ...
GarageType_Attchd         0     0.00
GarageType_Basment        0     0.00
GarageType_BuiltIn        0     0.00
GarageType_CarPort        0     0.00
GarageType_Detchd         0     0.00

[95 rows x 2 columns]


In [18]:
df['MasVnrArea'] = df['MasVnrArea'].fillna(0)
df['MasVnrArea'] = df['MasVnrArea'].fillna(0)

In [19]:
print(df.dtypes.to_string())

Id                      int64
MSSubClass              int64
MSZoning               object
LotFrontage           float64
LotArea                 int64
Street                 object
LotShape               object
LandContour            object
Utilities              object
LotConfig              object
LandSlope              object
Neighborhood           object
Condition1             object
Condition2             object
BldgType               object
HouseStyle             object
OverallQual             int64
OverallCond             int64
YearBuilt               int64
YearRemodAdd            int64
RoofStyle              object
RoofMatl               object
Exterior1st            object
Exterior2nd            object
MasVnrArea            float64
ExterQual              object
ExterCond              object
Foundation             object
BsmtQual                int64
BsmtCond                int64
BsmtExposure            int64
BsmtFinType1            int64
BsmtFinSF1              int64
BsmtFinTyp

In [20]:
print(df['Electrical'].unique())

['SBrkr' 'FuseF' 'FuseA' 'FuseP' 'Mix' nan]


In [21]:
df['Electrical'] = df['Electrical'].fillna(df['Electrical'].mode()[0])
electrical_mapping = {
    'FuseP': 1,
    'FuseF': 2,  
    'Mix': 3,    
    'FuseA': 4, 
    'SBrkr': 5  
}
df['Electrical'] = df['Electrical'].map(electrical_mapping)

In [22]:
df = pd.get_dummies(df, columns=['MSZoning'], prefix='MSZoning', dummy_na=False, dtype=int)
df = pd.get_dummies(df, columns=['Street'], prefix='Street', dummy_na=False, dtype=int)

lot_shape_mapping = {
    'IR3': 1, 
    'IR2': 2, 
    'IR1': 3,  
    'Reg': 4  
}
df['LotShape'] = df['LotShape'].map(lot_shape_mapping)

df = pd.get_dummies(df, columns=['LandContour'], prefix='LandContour', dummy_na=False, dtype=int)

utilities_mapping = {
    'ELO': 1,     
    'NoSeWa': 2,
    'NoSewr': 3,  
    'AllPub': 4  
}
df['Utilities'] = df['Utilities'].map(utilities_mapping)

df = pd.get_dummies(df, columns=['LotConfig'], prefix='LotConfig', dummy_na=False, dtype=int)

slope_mapping = {
    'Sev': 1,     
    'Mod': 2,
    'Gtl': 3
}
df['LandSlope'] = df['LandSlope'].map(slope_mapping)

df = pd.get_dummies(df, columns=['Neighborhood'], prefix='Neighborhood', dummy_na=False, dtype=int)
df = pd.get_dummies(df, columns=['Condition1'], prefix='Condition1', dummy_na=False, dtype=int)
df = pd.get_dummies(df, columns=['Condition2'], prefix='Condition2', dummy_na=False, dtype=int)
df = pd.get_dummies(df, columns=['BldgType'], prefix='BldgType', dummy_na=False, dtype=int)
df = pd.get_dummies(df, columns=['HouseStyle'], prefix='HouseStyle', dummy_na=False, dtype=int)
df = pd.get_dummies(df, columns=['RoofStyle'], prefix='RoofStyle', dummy_na=False, dtype=int)
df = pd.get_dummies(df, columns=['RoofMatl'], prefix='RoofMatl', dummy_na=False, dtype=int)
df = pd.get_dummies(df, columns=['Exterior1st'], prefix='Exterior1st', dummy_na=False, dtype=int)
df = pd.get_dummies(df, columns=['Exterior2nd'], prefix='Exterior2nd', dummy_na=False, dtype=int)

df['ExterQual'] = df['ExterQual'].map(fp_mapping)
df['ExterCond'] = df['ExterCond'].map(fp_mapping)

df = pd.get_dummies(df, columns=['Foundation'], prefix='Foundation', dummy_na=False, dtype=int)
df = pd.get_dummies(df, columns=['Heating'], prefix='Heating', dummy_na=False, dtype=int)

df['HeatingQC'] = df['HeatingQC'].map(fp_mapping)

air_mapping = {
    'N': 0,     
    'Y': 1
}
df['CentralAir'] = df['CentralAir'].map(air_mapping)

df['KitchenQual'] = df['KitchenQual'].map(fp_mapping)

functional_mapping = {
    'Sal': 1, 
    'Sev': 2,  
    'Maj2': 3,
    'Maj1': 4,  
    'Mod': 5,   
    'Min2': 6, 
    'Min1': 7, 
    'Typ': 8  
}
df['Functional'] = df['Functional'].map(functional_mapping)

pave_mapping = {
    'N': 0,  
    'P': 1,
    'Y': 2
}
df['PavedDrive'] = df['PavedDrive'].map(pave_mapping)

df = pd.get_dummies(df, columns=['SaleType'], prefix='SaleType', dummy_na=False, dtype=int)
df = pd.get_dummies(df, columns=['SaleCondition'], prefix='SaleCondition', dummy_na=False, dtype=int)

In [23]:
print(df.dtypes.to_string())

Id                         int64
MSSubClass                 int64
LotFrontage              float64
LotArea                    int64
LotShape                   int64
Utilities                  int64
LandSlope                  int64
OverallQual                int64
OverallCond                int64
YearBuilt                  int64
YearRemodAdd               int64
MasVnrArea               float64
ExterQual                  int64
ExterCond                  int64
BsmtQual                   int64
BsmtCond                   int64
BsmtExposure               int64
BsmtFinType1               int64
BsmtFinSF1                 int64
BsmtFinType2               int64
BsmtFinSF2                 int64
BsmtUnfSF                  int64
TotalBsmtSF                int64
HeatingQC                  int64
CentralAir                 int64
Electrical                 int64
1stFlrSF                   int64
2ndFlrSF                   int64
LowQualFinSF               int64
GrLivArea                  int64
BsmtFullBa

In [24]:
print(pd.DataFrame({
    'Missing': df.isnull().sum(),
    'Percent': (df.isnull().sum() / len(df) * 100).round(2)
}).sort_values('Missing', ascending=False))

                       Missing  Percent
Id                           0      0.0
MSSubClass                   0      0.0
LotFrontage                  0      0.0
LotArea                      0      0.0
LotShape                     0      0.0
...                        ...      ...
SaleCondition_AdjLand        0      0.0
SaleCondition_Alloca         0      0.0
SaleCondition_Family         0      0.0
SaleCondition_Normal         0      0.0
SaleCondition_Partial        0      0.0

[221 rows x 2 columns]


In [25]:
df.to_csv('train_cleaned.csv', index=False) 